name: nss
description: "An application for NSS MIT-BLR to interact with volunteers."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  phosphor_flutter: ^2.1.0
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.10
  custom_lint: ^0.6.4
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  assets:
    - assets/

  uses-material-design: true